<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_more_horizSelect AllLevel of Education _f91407</name>
   <tag></tag>
   <elementGuidId>318adf06-3871-45ca-8983-57a36b28ad4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount-vue-app']/ui-view/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pim-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mount-vue-app div >> internal:has-text=&quot;more_horizSelect AllLevel of Education arrow_upward Visual checkohrm_edit Rows p&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcf6836a-eecb-4695-8a27-aaca36fd6372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pim-container</value>
      <webElementGuid>a91b238d-98f6-4819-8e07-cc4e20df4bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horizSelect AllLevel of Education   arrow_upward Visual checkohrm_edit Rows per page▼1020501001020501001 - 1 of 1add</value>
      <webElementGuid>dc002fbd-1968-4574-90d2-b9309cc94691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount-vue-app&quot;)/ui-view[1]/div[@class=&quot;pim-container&quot;]</value>
      <webElementGuid>ec099d34-cf96-4c93-b4d0-a9390333cc23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/ui-view/div</value>
      <webElementGuid>7016db0d-fb66-4c5e-b158-c3edc70810aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::div[6]</value>
      <webElementGuid>67e3ef5d-fded-49b4-9e38-654be57778ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::div[9]</value>
      <webElementGuid>c803db81-fb34-4efc-8b25-d6bc27b640d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div</value>
      <webElementGuid>0e55ac5f-89b8-438a-9a5b-6da039b1c1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'more_horizSelect AllLevel of Education   arrow_upward Visual checkohrm_edit Rows per page▼1020501001020501001 - 1 of 1add' or . = 'more_horizSelect AllLevel of Education   arrow_upward Visual checkohrm_edit Rows per page▼1020501001020501001 - 1 of 1add')]</value>
      <webElementGuid>5a1559fc-7600-4719-a9fd-15d6af0615af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
