<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Manage Job Categories</name>
   <tag></tag>
   <elementGuidId>2be02ea0-0ad4-4ace-ac59-5c0229d6db00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autoComplete_result_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Manage Job Categories&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>960016c2-00d6-461a-adb4-aeb1cd3794ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>d6d8363f-5f24-4a8f-8aa9-524fda7d2306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Job Categories</value>
      <webElementGuid>25c79868-46f0-47ed-9f65-b357bfae9cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete_result_0&quot;)/div[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>e75d45b2-891c-4e2a-ba7d-231ac30942d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='autoComplete_result_0']/div</value>
      <webElementGuid>abb23bfb-5ff4-4b42-b96d-b2c632f8f3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::div[2]</value>
      <webElementGuid>75759d29-6867-4323-a841-d1a3764d029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::div[7]</value>
      <webElementGuid>2af47555-476f-4b57-8d8a-dbc29f695153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Administration > Job'])[1]/preceding::div[1]</value>
      <webElementGuid>a7de132c-686b-46cc-b5dd-d348e5b6c125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People Management'])[1]/preceding::div[2]</value>
      <webElementGuid>22f24908-cea4-479c-9f09-c6d39d0d5e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Job Categories']/parent::*</value>
      <webElementGuid>2cfdbc38-3a01-4b3e-9068-058e4644590a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>ac587bd1-5af4-4833-82aa-0f0749545cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Manage Job Categories' or . = 'Manage Job Categories')]</value>
      <webElementGuid>131da6c2-8606-4f10-af6c-21d0cd90bb62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
