<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_menuQuickSearchmenuQuickSearch (1)</name>
   <tag></tag>
   <elementGuidId>97c4cb7e-57a6-4751-8cd4-2f1f5aef4d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuQuickSearch_menuQuickSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89ef62a4-22d2-41d9-ad62-3d227d9fc889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>22b5cef2-a535-435d-b50f-6f4319d31aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d41e76b6-c5b2-49f2-b335-b6e090d1cb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menuQuickSearch[menuQuickSearch]</value>
      <webElementGuid>018a8926-b887-413f-b348-82e8ec7388b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuQuickSearch_menuQuickSearch</value>
      <webElementGuid>a6c4e14d-f18f-4596-9652-ef6aca43189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuQuickSearchResultList</value>
      <webElementGuid>1ed21744-f5d8-49b6-887d-bf2b1223ea42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>7c212528-fa93-4d65-8c14-f7901214ab42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuQuickSearch_menuQuickSearch&quot;)</value>
      <webElementGuid>abd06647-ad3d-47ae-bd6f-314e84af0748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>d24e38e4-21ab-4827-91ff-b5de06d29986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div[2]/input</value>
      <webElementGuid>092a2221-5d3f-4d56-8ce1-f7eefb61a561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d0a79019-ec92-4969-80b0-5c86d1e517fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text' and @name = 'menuQuickSearch[menuQuickSearch]' and @id = 'menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>b4c97eb1-c43c-4e0f-ab1b-bd3ae5bcf039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
