<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_EducationEmployee Management  Qualifications</name>
   <tag></tag>
   <elementGuidId>8fdc38ee-d7e4-4f36-bbf9-37bf0708e8e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autoComplete_result_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autoComplete_result_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Education Employee Management > Qualifications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7608f52a-2d3d-4d25-9c59-d65c4fa003a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete_result_0</value>
      <webElementGuid>4adfa8ef-1f3e-417a-9694-e2da42d74958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ae24b037-0a96-41a3-ac00-356e17aefd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuSearchResultItem</value>
      <webElementGuid>1e36a674-e909-4268-b51d-ac4e5d3d3f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EducationEmployee Management > Qualifications</value>
      <webElementGuid>03f3d882-b9b4-4ba0-a264-a1a73faae549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete_result_0&quot;)</value>
      <webElementGuid>7b44ec90-d58a-48ff-806f-29ccaaaceb2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='autoComplete_result_0']</value>
      <webElementGuid>eb18fd5f-7dc6-4500-896a-190ff6be0b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menuQuickSearchResultList']/li</value>
      <webElementGuid>71eefad4-84f8-4253-a485-bacb28e674bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::li[1]</value>
      <webElementGuid>b604d74e-2f5a-4dd8-befd-df2b3404fa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::li[1]</value>
      <webElementGuid>1fb19b7b-012b-4542-9c4f-fd57dc913e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>d842ff52-1e29-4964-a55f-d4fd9095a98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'autoComplete_result_0' and (text() = 'EducationEmployee Management > Qualifications' or . = 'EducationEmployee Management > Qualifications')]</value>
      <webElementGuid>97684c6d-76dc-4e82-9ecb-3859d6600685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
