<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel_materialize-lean-overlay-1</name>
   <tag></tag>
   <elementGuidId>88655c55-5fff-46f6-980c-5a6712c0e60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='materialize-lean-overlay-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e386a927-a1a7-45f5-aff7-5504ff024598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-overlay</value>
      <webElementGuid>e610f2c1-a810-4591-9781-bd476df1993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>materialize-lean-overlay-1</value>
      <webElementGuid>b3512971-caef-4f32-b1c3-632b14000368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;materialize-lean-overlay-1&quot;)</value>
      <webElementGuid>6a0623e8-3dc0-4ec4-920d-83404ce6a113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='materialize-lean-overlay-1']</value>
      <webElementGuid>326c887e-aee4-412b-bb50-0df2cc083f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[64]</value>
      <webElementGuid>83892a2b-080d-4649-bc60-d9666b07fae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'materialize-lean-overlay-1']</value>
      <webElementGuid>c8979c89-9df8-4e95-8de3-adaa37b0be21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
