<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_more_horizSelect AllJob Category   arro_cc7f56</name>
   <tag></tag>
   <elementGuidId>dfd78c7c-d5c5-42f6-860b-529fab501fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobcategoryDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobcategoryDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jobcategoryDiv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d930f23a-9d91-4dad-bc17-ce10224cfb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobcategoryDiv</value>
      <webElementGuid>daa4cace-78a6-4282-9f75-61fedbd5e0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add</value>
      <webElementGuid>b5857a1e-2315-4bb7-9e7d-d5fe7616b867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobcategoryDiv&quot;)</value>
      <webElementGuid>8610acd6-55f3-4a71-b2b9-8cc6b5a6741a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='jobcategoryDiv']</value>
      <webElementGuid>c5e87d2e-6812-4b51-bb15-6e5b690dc72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/ui-view/div/div</value>
      <webElementGuid>db24cbda-4e33-466f-bd56-ae8fb307fa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::div[7]</value>
      <webElementGuid>48ff1c2a-7883-4379-b013-cfc05cc3922c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::div[10]</value>
      <webElementGuid>fdec4147-e267-407f-93e7-37deb0861bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div/div</value>
      <webElementGuid>850cd45e-8e19-45b6-b0fd-ab4389c98b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'jobcategoryDiv' and (text() = 'more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add' or . = 'more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add')]</value>
      <webElementGuid>88c597e1-79a5-434a-a436-c7eb40b52297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
