<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_search</name>
   <tag></tag>
   <elementGuidId>8fa720d2-ef46-4095-80d4-d9eaed0f73e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-holder > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-menu']/div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6af7d71a-f8d9-4c8c-a221-fad77f31b013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>e980f069-1d55-4931-94f3-5babdcb121e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>923b402a-f0cd-4894-a8a4-4ba77909fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-menu&quot;)/div[@class=&quot;sidebar-search&quot;]/div[@class=&quot;icon-holder&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>9fd4ee77-b15c-4dbe-9683-c46a55150513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div/i</value>
      <webElementGuid>bb848d2b-1550-4cc6-b61a-24cd40bef95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::i[1]</value>
      <webElementGuid>eb2294ec-3f9f-45ed-ba5a-089582ac925a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aaron Hamilton'])[1]/following::i[1]</value>
      <webElementGuid>4910d44d-406f-4e74-9750-aa8daae48500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People Management'])[1]/preceding::i[1]</value>
      <webElementGuid>d10651e8-52c0-4a50-89ad-b30d177d4e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Administration'])[1]/preceding::i[1]</value>
      <webElementGuid>5b35cc85-cf87-49e7-b801-1958f46dca6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search']/parent::*</value>
      <webElementGuid>a37eca02-dac7-4691-a7fe-5d077ec223f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>19408c1c-e7a5-44f5-91b3-53a7abd124f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>85bf4073-21e2-4cc7-ab59-40a5cec06819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
