<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_menuQuickSearchmenuQuickSearch</name>
   <tag></tag>
   <elementGuidId>d7130485-6512-424f-8ae2-0ad7bca0e175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuQuickSearch_menuQuickSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>703acd77-f62a-416e-8c08-8c60358732b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>88899c91-10b3-42c7-996c-573e90d64323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7702d686-80a0-4f9d-bfcf-d23b7aadb45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menuQuickSearch[menuQuickSearch]</value>
      <webElementGuid>a77be35c-0479-4903-9ef3-d513df539028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuQuickSearch_menuQuickSearch</value>
      <webElementGuid>82f8e911-8277-45f2-94e2-1fbf6028dad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuQuickSearchResultList</value>
      <webElementGuid>28ecd9da-2a1a-457a-b7e9-ea87a6d55a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>b74e6e48-2030-4272-ad5d-121f83a9db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuQuickSearch_menuQuickSearch&quot;)</value>
      <webElementGuid>bb14bfda-611b-420b-908f-1dd45c186caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>532b5320-ef7b-4e57-95b4-cbdc246252d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div[2]/input</value>
      <webElementGuid>1f1db2bd-4cc0-4ee2-85eb-3622fc823524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a7966faa-83c7-4ab6-85a2-4851578994c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text' and @name = 'menuQuickSearch[menuQuickSearch]' and @id = 'menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>5948a09e-096b-4ed5-8fe9-c1ebc8441394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
