<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>0762e495-72f0-46f4-a805-2b39922de04d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.modal-action.waves-effect.waves-green.btn.primary-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b7ba74e-29f7-4a47-903f-d64da212d1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-save-form</name>
      <type>Main</type>
      <value>modal.save(educationModalForm)</value>
      <webElementGuid>79ca3786-d0dc-47ab-9866-6ffd9e100b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-name</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>30918cf0-9ef2-49aa-ab7a-95f2bf184f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-modal-on-click</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>1e8ebf08-e2f5-46b7-803a-31d9e7e0abb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-action waves-effect waves-green btn primary-btn</value>
      <webElementGuid>de7d2d0e-49ce-494c-bdc9-815f3f9a7fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>50af6731-db04-43f3-9f3a-4f2433b04054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-valid ng-valid-duplication-education ng-valid-schema-form ng-dirty ng-valid-parse&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;modal-action waves-effect waves-green btn primary-btn&quot;]</value>
      <webElementGuid>a52fe9cc-84b6-424f-9b91-28fd6cb32c80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div[2]/a</value>
      <webElementGuid>4170b717-4b59-4548-a30d-02b9811275cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>353ab017-bac3-4abc-872f-0dd8874ce8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>879968d4-c261-4bbb-a217-e2c23c7a2f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>88f69f67-432e-41a2-9ea8-fbf5b4a09e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>5bcb88e3-bf1c-498b-9398-2c4cca570f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[81]</value>
      <webElementGuid>7e187d65-4487-48ef-9cbf-76b713ebe709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>31deaf96-785f-44b1-95d6-ba7012bbe2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>eea1167f-b54d-4d46-86ff-40920cd0bc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[79]</value>
      <webElementGuid>6f78bda0-f1e2-4801-97d1-eaf9e13e3487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
