<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yes, Delete_materialize-lean-overlay-1</name>
   <tag></tag>
   <elementGuidId>0dd8f40f-b642-456b-9143-f32baa63fd35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='materialize-lean-overlay-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11c71aa7-e89a-4732-8633-b5d3b3a829a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-overlay velocity-animating</value>
      <webElementGuid>bf2fab40-d771-401b-b8b0-f779017bc4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>materialize-lean-overlay-1</value>
      <webElementGuid>46085f58-3362-4a7b-8ae5-29486a402066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;materialize-lean-overlay-1&quot;)</value>
      <webElementGuid>3b310456-1c6c-4fee-937e-9ea1e1c894a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='materialize-lean-overlay-1']</value>
      <webElementGuid>aee6b8d9-75f5-4d25-bc44-985feba3babb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]</value>
      <webElementGuid>f76f9ac9-3d03-4972-9b63-93aa79d4efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'materialize-lean-overlay-1']</value>
      <webElementGuid>f2656078-59da-49d8-bd2e-a00966820506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
