<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>d2f42d01-c625-4b4a-be58-f4fa5b7c22b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.modal-action.waves-effect.waves-green.btn.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80285173-03b6-41ac-ab52-fe605e18b5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-save-form</name>
      <type>Main</type>
      <value>modal.save(educationModalForm)</value>
      <webElementGuid>0f3940de-0efa-44c3-9906-3a6f5d61e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-name</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>91fb9de3-3888-451a-a93b-e2cc7fe33f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-modal-on-click</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>3fa93f67-4056-4651-a0f8-f46e692433f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-action waves-effect waves-green btn primary-btn</value>
      <webElementGuid>1da1767d-09bc-419a-8d98-123bfbd4366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>26603b2a-504f-44e1-a471-ffc127d8a9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-valid ng-valid-duplication-education ng-valid-schema-form ng-dirty ng-valid-parse&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;modal-action waves-effect waves-green btn primary-btn&quot;]</value>
      <webElementGuid>20148591-316b-496c-aecd-baf3a0478f9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div[2]/a</value>
      <webElementGuid>06aa6a58-d8e5-4cd7-a25b-2ec448f770d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>d7f78b3d-69e2-4e81-ba92-549f01549262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>08d87784-1f99-4728-9192-fdf29c443705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>8e92b83e-ce1e-4bc9-93cd-f5f0a789085a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>b54367d7-2bb2-4089-b59f-45f9a29f3b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[79]</value>
      <webElementGuid>3aca2d7c-1193-45cb-a417-611f27627f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>87391817-77dd-417a-bd84-34e4772a90d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>8a97269d-1491-46b2-9122-f1ca3b99c4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[81]</value>
      <webElementGuid>05954b20-da93-4e50-9c62-e0cd35747d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
