<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>8915957d-a575-4a84-ac70-322617f857d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.modal-action.waves-effect.waves-green.btn.primary-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e424293d-e171-4d40-b1a3-b16e4f369bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-save-form</name>
      <type>Main</type>
      <value>modal.save(educationModalForm)</value>
      <webElementGuid>913610e9-9254-46a0-a9e0-36ee7f0e63fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-name</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>e24cf8e7-11a1-4f89-95d0-c62eb73a90c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-modal-on-click</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>a0d5a5ec-6e2f-4ea5-ab3b-700165171f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-action waves-effect waves-green btn primary-btn</value>
      <webElementGuid>84e57863-d9ce-4275-aad6-55bf3e3085e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>fe1d72f9-464e-4510-ba2d-6a92d5836b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-dirty ng-valid-parse ng-valid-tv4-302 ng-invalid ng-invalid-duplication-education ng-invalid-schema-form&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;modal-action waves-effect waves-green btn primary-btn&quot;]</value>
      <webElementGuid>619243ee-40c2-4b54-b223-bdbc3ae4c9d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div[2]/a</value>
      <webElementGuid>fa7020e8-b622-4570-b319-df84fb3f005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>8cf09fea-bc6b-4a1a-968e-24593e046f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>566fd275-e138-4fbd-ab83-9d48fe38833a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>89cac26a-7438-45a9-b951-0cdd606a0bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>51e56798-4bc6-4a87-8b9c-8f3bb6c79a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[81]</value>
      <webElementGuid>3973fa2b-6b9c-49e1-9034-91f475994438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>9aa170d2-6e9d-453f-8e06-75b3b713b0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>203e07ac-7823-4d5e-88d9-21547fd19e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
