<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>53adabb5-1f93-41df-9599-482765cea0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.modal-action.waves-effect.waves-green.btn.primary-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf3011fa-8b85-4c5e-a831-37ccf4059342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-save-form</name>
      <type>Main</type>
      <value>modal.save(educationModalForm)</value>
      <webElementGuid>1417559b-4453-4933-9ebb-b77f131ffc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-name</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>a0bc65a0-0bd6-421e-8728-a1fbb41639f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-modal-on-click</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>f7ffb371-199d-46dc-a4a0-f416fd23f87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-action waves-effect waves-green btn primary-btn</value>
      <webElementGuid>c114f069-e025-4f4a-b7dc-0bda29e90ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1aec1e07-a669-41b4-98b9-d6ebb08dea38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-valid-duplication-education ng-dirty ng-valid-parse ng-valid-tv4-201 ng-valid ng-valid-schema-form&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;modal-action waves-effect waves-green btn primary-btn&quot;]</value>
      <webElementGuid>a2d676d2-f719-4a3e-8853-e63eb0f49dcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div[2]/a</value>
      <webElementGuid>0fbe6814-182e-4c1a-a955-f7cd645ca99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>63d44970-00e7-4361-82b2-aa7694ddc24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>b54f5232-369b-4e84-9fb2-d34707ddec33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>87bb57d1-9395-42bf-83b2-3ad6a236e02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>90f10025-737e-4cc5-b95d-e7bf365cc58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[79]</value>
      <webElementGuid>32990868-7c4e-46a6-b575-b24b60d0f301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>340d6cc4-a397-4ecb-8dad-51a8face9f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>38302d24-1545-4228-a981-986062d817ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
