<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel_materialize-lean-overlay-1</name>
   <tag></tag>
   <elementGuidId>4b94a079-9a11-4f8d-972b-f63a38b508d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='materialize-lean-overlay-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8967acb8-2363-44da-b9c1-a6b88e4b3274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-overlay</value>
      <webElementGuid>5bb4b72f-b4bf-497f-bf46-c75263f62abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>materialize-lean-overlay-1</value>
      <webElementGuid>91a781c0-c3e1-4381-8c4f-c759db487344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;materialize-lean-overlay-1&quot;)</value>
      <webElementGuid>abcbdda5-48d6-4a78-9bd7-4d6356c7babc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='materialize-lean-overlay-1']</value>
      <webElementGuid>bec60acb-1b97-4447-afdc-769813dbe038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]</value>
      <webElementGuid>db63268d-7d8b-4bd5-a78d-5df11f7b8f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'materialize-lean-overlay-1']</value>
      <webElementGuid>5e69ada8-36a9-40d9-a418-72378ff75fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
