<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_more_horiz</name>
   <tag></tag>
   <elementGuidId>be2816ad-b9f0-4ee6-9b0b-a857a99aa8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.icons-color.orange-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;more_horiz&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>af9e8b8e-7d95-4a23-82b9-65dd8b7979f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons icons-color orange-text</value>
      <webElementGuid>b58b7845-aed5-4d14-99d3-4fcbf3e2a9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'orange-text': listData.selected.length > 0}</value>
      <webElementGuid>3a4b0295-2cb9-40e3-ad77-1128a1b1ff62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horiz</value>
      <webElementGuid>055fd1ea-77f8-4cfb-aecd-f3fa895b2363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;list-options&quot;]/a[@class=&quot;dropdown-button dropdown&quot;]/i[@class=&quot;material-icons icons-color orange-text&quot;]</value>
      <webElementGuid>a0275521-caf9-475b-9b45-b35c58b26f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      <webElementGuid>df9f6aad-c479-43e3-a29e-e9211213e8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::i[1]</value>
      <webElementGuid>44795916-0eac-4ee3-805b-21cf4f9a9d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::i[1]</value>
      <webElementGuid>c8e73b8a-61c4-487c-ba51-466364dfdcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::i[1]</value>
      <webElementGuid>c7994a00-28da-43a2-8919-701a142b3b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[1]/preceding::i[1]</value>
      <webElementGuid>cdb5d7f9-d60f-4653-b03e-54e908d5249f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_horiz']/parent::*</value>
      <webElementGuid>21d32f6a-5fe8-485f-88b4-913b17f958e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a/i</value>
      <webElementGuid>bd8d454c-833c-499f-89b5-5854f5ba0dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'more_horiz' or . = 'more_horiz')]</value>
      <webElementGuid>22cf4a0d-709e-4b71-88f9-5710f5b39861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
