<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>5b1125c9-6613-46d2-8429-83f7ff6af407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[3]/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;ytgh ohrm_edit&quot;i] >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b7ba18c-4e92-4152-b915-ad03b5c7bba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkbox_list0_19</value>
      <webElementGuid>20daa057-b647-46b9-b2a1-b64faa29ad32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[3]/td[1]/label[1]</value>
      <webElementGuid>540c462f-b35c-453d-8d8c-691ddf96eb22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[3]/td/label</value>
      <webElementGuid>ef111542-fda7-4f28-bb96-6a1e72bc4e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/label</value>
      <webElementGuid>7b0b7c86-6e2a-4e42-8f8e-d5a776a4b952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[2]/td/label</value>
      <webElementGuid>756de6cf-aec3-4997-9e0e-272cf2cf3691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>af3a850d-4398-4852-b093-e76cc12d1d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[5]/td/label</value>
      <webElementGuid>fb40b327-8e26-424e-9257-a8c46d3796e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label</value>
      <webElementGuid>92ddabbc-bd91-45b8-9f3d-93aa836c67e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[6]/td/label</value>
      <webElementGuid>e46d1639-6935-4f1d-9b0a-c138d74e0c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/label</value>
      <webElementGuid>0703daef-c50d-4f7e-8dae-89a120ade645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
