<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_menuQuickSearchmenuQuickSearch</name>
   <tag></tag>
   <elementGuidId>7fe55697-ce87-4aed-9437-724c52d6ab47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuQuickSearch_menuQuickSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93c896f6-a7e6-40fd-928a-62fe446741a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b0c72a4e-4493-4954-864c-3d3905efbc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17e6258f-d074-4970-9ac2-9fc70a770f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menuQuickSearch[menuQuickSearch]</value>
      <webElementGuid>4a2cedd9-d9ec-4459-a96b-cd7a25c23de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuQuickSearch_menuQuickSearch</value>
      <webElementGuid>493de65d-c166-4652-b5b7-fe2204bb17e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuQuickSearchResultList</value>
      <webElementGuid>7bdb9c46-55e0-49fc-985d-1ba92b34b1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>47628064-5ff7-4e98-8590-abd9980f647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuQuickSearch_menuQuickSearch&quot;)</value>
      <webElementGuid>83855e3f-1b51-46e2-a45d-5ffb57b933e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>9468d700-a29c-41a5-b620-84a2e8c77705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div[2]/input</value>
      <webElementGuid>8607571a-68e4-461c-85ed-bfbc2ebbb1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8624efbf-0b57-472b-b46a-a9177cc7cf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text' and @name = 'menuQuickSearch[menuQuickSearch]' and @id = 'menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>95a12bb8-708e-4608-8929-c7615c43a6e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
